apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCLcAY1gMD7MKpZvgYjRlLPPanD9PT9eNgjfoolTDPDaJUhLQKyQtz3n9pj1Mc1iUTjIcblz/H3deLXCxCKOj6pxuJjhJbFC27qDSVszckc1BS/QLJJRDuExrlpq91c33FWoAqtK2NZb0gdsAV+eZwtvpOZTfQ3eXcAiO6ZIh8kuYY51t8N/1Oqur1Fr/xJKRpCHUMrqJwScZWug4kG+v4ZuWH9C7Cob2exH8Kyoas0RhLETVO9xia2NnXJ3AbRjFGGFkKY4c4WehasovReU7jvpd4V8m2LO2c+75AIPsAB2Yo88jqNbKpUiPug14s1v6bYW3TnJ8FzkdoUqWQhec97tWSpTEU2mdAJk8J1Vl79adKT2meP8dr5wDu/JNPBpEqKTs9Z8Poh7Gp8R4w6GO919tYSbWLefO66aUtbhjft1sfcWTgQlsYAb4UKkbaSZ31WtLnJChcNzEE8KbpwElxIKxtZSVn25JpS+nEsA0G3lMljttymcbku+0cPfKLu1W626U+vlW9W5PpKdwHOLA4NYjpu/C0FF3lQhVzBnrcjasQF0GQr72j4vGZtNOdH5+l7wkR9QbW6paD+y/ZcWRzjD92GZpA7GKAnvJkFDTPAFnOqmcv/d0XOPGJsfF9a5iYbzCfz/+zP/BAAiysGCjz7z54Hs6Gnx/EjP1L9vH77MGjYbJHuHnJ/GGUuL7t549U98+3OXJWuTUN+K6UScBVNTrlCbkYYK/DzRUqu98CpeFhrVlxU/GNNsPYe/EWGbXXbODOUa+9O8VOIlKIepcfYT/lg8+zf8rm8oX9Npn/sGeGrwnK9sz2Dg0p8xteDUdXsDtpNzEsBO7VzLzzLwTB/2BTJWRls5xXeXes2qd29UjlcCd9JcEKq5iTcjQzfegDt8KdNH/3jvfIvlHnK0Yy3xE8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

