apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAO3VoTV1109Z6fiNXm4IdnYpP3rq5qw1er5axAdbaLVhmxDYjYqPHfULL/nrRG1bp9TH12QGV5CIMw7Xx8HqnRC+f9iybuB5d3QkZ6UkYVz3rCjD8mZ08+SaqLwPnLZ2gfks7jDnccR7YXJrmY3S1FemfRLqZfOmXMUG8VfStXbDCwHMHoVS91+Uu+WILbaoVWnHffvpWAHEFfmgmfE9nT2sBgnFpby9eIga8sMzus+LKGu7Gr2kzkEKoSwtnUISw5d2msFxIBEiT9zsf6L6a4zuIgwZw9eugdqzbpApp6cf2HxUt+v4Fsq4p7Q0ebv+J7FyASXD1srGjkpm7hnJnPuoqEp/f390GkCLGyBSp57/sQ2klmbYGbWgFtJkdC9m35pAYa0+yn7m+4As1dItIeNzNMI6ZhKGhhFKF8iC9i5oMycouGeg2QFip6wgH3En3LxAR99WMvZzAi1xq5/8D8LaxqfYeXTGU9Fuk4xHIPShGXsaXLi2Q7X4ERa7vhl8+mSAIY7UxPD+EkBHyGkXE4AAR7DN1ljVgMV/JxRZvk95/AAOQJzNGm2dR5GC39BKDQ9thaRYbKiYk87T+Wuvh+wU/l7HgwvZ+ALND+LzFUgdwOATh4F1Mkeu3zWCJ/ihE2TF1HntzcfFc1/U7ltfoIWeedyfiV8z6QJ7O9kITbE3ZZ1paAGO2WM2bW4ddaMGWXEh9W0s0l8iedQjRrJAc03PaTsKbr9ZYwqVSoVQLe0OEVTNdO9dwRktUMfHTV95Sm+WGIXJYd+Z02RVzSxUF1GP82x5z6p8ldBbkLEOKLh1SmDRhY9TtRAFVb29xIH4sR8sxQImlLaawMQWtHr0gJMbG7SkDqCyIWhQ0bJdtbXs9jK0jhh45W3ICm70KdNCJi88dqdOP7TfNqSuK930JdB9s=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

