apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAMnUk+Vc+Il5vK90eaPPYRTPSo6efJS5lx+B7tzOzLvMHvh+1nDtIct5EfVYuay6WgjMUS32auOTM4Xjq3Awo8EnxvA8i+4RpBau3ucteldNRrinAd8rJR8YBGbz0NRHPw6H+tLf59rdo0dJ3SxrzYvW8P4sb4W6DsiUVaWLN9u9r0MfqlFxRb14C2Tu0mhvWii4Hy6VuCBW4cKEtaB52Nlke3BnAPcjgWe95csvqgvLoKgvjfSZpebxqGN9avUdOgrofY5ifKvddGb8hoo/559vPUmMhNZJkqkSDUtGx9LvCV/z8J8xjDR32wJX/cYAqxynYQMRptGcVhWRwq49turdzTQnvc1soibGWj6EkDhTEPo6ha2tyIY0mFgyjhM6q47GIyGxiTxCcPQDPWRiHmMVlit6RnSCUyRNO13z1oLzLFUrZ+FATO1bjwovvZI6wXU6XfISCtqu+Y3NzrdNojRaZo913Z3CwjUCmxgnfZEM2QGGXmGr85TVX896Lea0Q2gdclJ2qlJgs3ltCoYwru8DJVzstH1++U5/RUv8Tw89rp3LJMIVWe4A2yj24EE7KoHCpEHZGumzkM+I2YSm/JWhf0HOiEGgRtyjudOzCqgBknInmQy0FbByzr0Rz2FJvxTL5tii4q0B1jn8DZzPsq+l4rTIl6hOaSWIPLE/kbRaeidZ6sGm7yMrGgkr8ltXl41kS4Wl4DXNi9V0x+4IefRqT1+kM0Zwg2RKcu8ylRUKiUmK4eJG847dIdZATSOXrAYZ/f9mQflMCEYNFPkX5SBe2Oa0fdX9AOfj++KP+mw6aft82vv6mpa9CXwQmavzMC7rN80PFC5m5eFxbku2+RUIMXm9NKw5JpafQGC/hi1PvRwqiHjJlmhQ+1SiBVj7KhujaaVXTnjFMh0pI0OEbJo/L8aIjNGv8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

