apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA65lws0PqbfQlKNZg3nPRz6ZJKaSFSEZEq/SAF0LtvQWlZyE4jlNKrvob7/MwR3KdF8CFhgCJr/9MFNs2iRKC4diGf3cYvs8KjS3rzwnXQGkr/rMlFfd4NaSqX4bwfgBMljqTPFp/L/rX9TdIgAa+3JO/4/5jxkmEm2e8pkKstsC8kH7y/X2XE7hb4WKToMrpzestFT/MZvT1Lioa4G4aDf/vpWChpL0tgztwP8r/CnfF1wEV7JEdTkPezORttamM0zr+SgHuAO0CsmAridh0hrTE1LXaEFS2W/goOC4AE7xD50Q9oiWSPIIDtvhwnbVvPFVm0LwHgp/j4FDxcTxOLIGfkmNPFPVbyBjqjZrHc25fD/3eIplcdRUNM2ALqRM0Uy5U36gsAm4I28Y0zyJl6QLry4KF4Vp2eRKFZGncm8DsFpLCkW4Bb5M5XsnGd6qH8xbc/Y+JTqkOnx6ZlBRDkztb3fqcggmKVyNX8T3ljfJZ2pPfx+fLZDV8N2tx/FxQdh6tFU4OgiU9gu1o5gt3gsQvoHZZ6GH2gXL8tz9Q8Pn69L6m0VizCglKFR941v8grNXM/hnAdWAiTwLoAwYGlvru4JbAef/ShaLcETaR63MRC4BdG2dh16jYu/DTpGCM2XIWg1xVG0chl50reZGGjc1MhYkrW9zU6oEiOWtuLY5YYeXWDa4tcsZw7NZc0b+dlgwZDIMk1K9O5GEFRikEHEA3OPsJKFV8688r22gzBCHujOXto7VTbrl2ijRzWYzvP7wFQ01eaU+HQQsO79B0LlrktyAAIFnO+kgQIn93B+HdmU1LgGp8ZURbnftytbI9KIM2w9CnjcjO0iUYItDPNfoqzC0Igv+orDYmFfayvBz2agDZE4GgVg14sFqaZy0/lX5gZK7IISLX3kuh6fo1eUH+ce6aMPQqH4H+B42CKSgZdy5AlJizzHeU3p/rB6/KfBpBG/R4SbLFf4f4vlVYvr+7UVROf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

