apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 14.6.0
    chart: prometheus
    helm:
      parameters:
        - name: alertmanager.securityContext.runAsGroup
          value: '0'
        - name: alertmanager.securityContext.runAsNonRoot
          value: 'false'
        - name: alertmanager.securityContext.runAsUser
          value: '0'
        - name: server.securityContext.runAsGroup
          value: '0'
        - name: server.securityContext.runAsNonRoot
          value: 'false'
        - name: server.securityContext.runAsUser
          value: '0'
  project: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
