apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 1.16.1
    chart: sealed-secrets
    helm:
      valueFiles:
        - values.yaml
  project: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
