apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 1.16.1
    chart: sealed-secrets
    helm:
      valueFiles:
        - values.yaml
    helm:
      parameters:
      - name: commandArgs[0]
        value: --update-status
  project: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
