apiVersion: v1
kind: Secret
metadata:
  name: bitnami-labs-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://bitnami-labs.github.io/sealed-secrets
  name: bitnami-labs
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.bitnami.com/bitnami
  name: bitnami-stable
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://prometheus-community.github.io/helm-charts
  name: prometheus-community
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-state-metrics-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubernetes.github.io/kube-state-metrics
  name: kube-state-metrics
  type: helm
