apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBt8s/xtjVJT25Qd58CTxekTt0+CvMrqMyjFjb3E7+JFBVLVreW7tgzly3NBlgpTqX+ARBq1qbVnJQ6tcS2u5ZyNks0BA/NyVh/qzu66Vb3Ax+DS/VuZyx0SI95tZ6GWJwsqCFR50IUWyUCcikZHxqyNh7+yoU6S1fWo+fPZIqLEljc/rLJNU2xuBHeSc7P+0amVSAnNvYOZxFSX9KRH5GQrFJWzr4B9tpUN+7fiLERLVS3S1orjEuZzDgobNY4mDrLXTPMldsQYnnOCxbcGbeiOsiTlPqoOdIqYMngrY99u5vcYs8FZIHilCvAdnOot6UDpAXy+6afWuj2IggFB82k2AXaNbZYUdSS5uUn/6XcCCSnagyxgVUaNPYnyGpvn/0FE63WU1aMmrYkF+D5IWzSwYHE3dl7SJkCGKS5/cs8tNdQY6ogn3S5fBgZQdJv9D/gV9XVg6j2qMITz5AZMOzfb3rTRbnFE6x3Hd8sTlczVPlYX1YEVxGTj9ekifbYFa7dSIpIQZioe/FfoTy+W0Zg1U7DVJJ/ykCJXU9ieVm0VlU+SFu+CZ12ijV5Nw4KgXkxyFJQ5XgThrHG+9lkdKrmBnrQO4MN4qyp243F/wULPGgwrKrKVW9VI7yGG4O41Fdn6OyirxAa+uEEBlFyfAVU7rjuk5oir+t7A84zlA/3m+ppq65ZlJ5ai3vBI9LTvqZZpLL9u1woN2+wbvIOu2FRnji0w2TeIcCKcZdYBWHPPtGVfi7Cru0P
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

