apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCRuMDohpt6fhLgepDe4d9s0xh7B36nNA6i3RmI2JVLLfx7clSTe2qbR5smTRyVo7ATh1KoRXMuQZmGTOVAXE7KWZ/qtlyFKbbCah1xs+SrwsqrEXwC0TRto7cwlvS5SKvkPedF5tQMlqpo+OqwTeHTZaqbsCHiV55qvNZMOo+30atR2nUI8+/vwHiqyzybUZW7pL0agsiv9PXHpO9Og1pi/QAZpnAuScgO1p/IHwYgFv57j9hm8XWjGiS9Jw1gLR+hyILcL9xZIX2/i1uWpTvsSoIi4koM673VNRvDZBY2WNqB0gEaJn/etPR9weIjUArVwqmsHW+YaKP4F16MFEzNKCnMUKf3TTV+Kpr1HOFUnyOvzNBYTvtYxKCJPKVeWWDEsDof+WDNlNegk2ACrvv70Ysvs75AYnlVparmJm13hxR6wzB2B6dHfuSlES+tVGYz0nUo0xUL4HsKPZ6r+7SHiMtNSAx5p2fYgFcKBa5kIUeuIKjM/x7ll98qeEWfss5mkVYQrK2cJEPCRt+6hHKSSPh8Ew2yTlYr3qNOmCLrOpvfNmugTEHC1bpbdmBFokv981bp/TKzba8/+D3D0WI6DLoAkqQ+ua04U/m2YL2QEtIePpgMDobP0IfIlXOEWGIS0UR0nWPPvweK3RU9uh1Ioa9xw0/iQ9ekF0o91DIFAEnTmeTsHv6AMA0vYv+Eadc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

