apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCbFaSvCZGoqlRV7UACtBrY9/NzdUTeX29wXOivI5dOFXOVSwhxnq0QjzGr9QECktbLgD+9TwLtGCQGUwVszYugT7eAswOUkucB+u36f1H19Eg1sxeZ1KVvMGyySsosfXdX0zQFaPTIik7dacWdnAkQChMDZQgWeYL7mEPUE76kmh2dW6efYJrrYdRj23Z1KgQC6/vcykDN3stiGAbk8tQosLTtth+jHDGO3GiDgFreGzuSCRiIvpLvEbds4wdaBUZVByHHk/eSRkBbGl8HY5sTKZaY8kZHfJ+sCY7NyZaokfink0G2K3PgfLL40qwOt7D8+bBb8VZYUVEXOHQydhUSg+JjjUcf7W8RjZzfxfUWeDTEPjQdpXP+k5/FCw5KNJ2E0aEN+x/CrjAqFn98PLgKOTcNAl5xkT6JgZAta7j9CIklpICFBpVpbdqhF6k6NR308wUYJkZw7REkeiT2+NIPUvsI6HnW/MOGy05M0oiK9lcOX/qCQIpzlMsoVhUTeFLdApNut6PnKORSLRQnz4AJAyLalaaArPqQOX2648/C6ROmTXBgvWDvm+PEBtvr6iKIFzOA2fMCIj1DBpKeFr4E20OZ/d/UgTA5bgeSt4WrWSWmPyrEIPoS2rBHpkLEqmei4JZI5HI3wg7cUz5d3axmYu9Ql/L14Okej4cMY1529c9R7od2SE7EYSyAaGCG1SM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

