apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBhxdjYiBJyM0XN34fM3xe04LmH64jiTZT0T5d3GV3UCE2iN/h318HG/Knq8llHgejyQdq31GddBbdVfzJF7Ozwi2hS27A/+ICSwc7HM+Zi/JQ6yBwQJsiXgJXfov7fXxdOkTqss2YSGoiCEIRmkFYGs/3KdWyE1l2tx7qcRx2UNOMUBne2e4RG2wYbo2ftNyCr7m8p5BKoGUhYD0UZSbn5b5P4WlkdSe2+Wcd/WMo1RLRZNSOzVUBr5ihHr59kwaeMI0wwOteazigO4SUaTx1WyAGNVxCCrfiTqIokAShVfTtcFldRsSKEFCMkMHGFN/aH8/zNRl2Ak90QQ42m2pqMF6+BMKwjMEyU/o2QALDC3a7Ll0utcT7ourMhcjTYnUDQg3s3+FfNwqADfLT7RMDVrB1WoLJpZOLvFwNeOE17sWiE1nMlymfntYLvZ7lAC8cv9rEqOtpPdwQUdK8kHmJAnlT7XOAV65lahO21fooehWfThFLXcacOHnSDjAt8Fh9RJDei8VJ1OavNTMwCM9Ye711CIq9amL/68ZgMnjYBLfqMCxzRuIZptOOwB+Vn2r+LIzDcPaWvqpC75mXRJezTqcFVPEsDccVXH9gwgKY25yExvvdDqK/4vU9NBENI0uK7qEOfA5p7rIlFIqgilf/jJbDXBHf2rWwQgwAPyyKxmiH5V0gYGbdwI6ryQetDdSk4resPDnw0Jlvr/qkU2kFBNqZxFFpofcyYpVzORnzEtfe6omgQtbiV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

